from __future__ import annotations

import json
from pathlib import Path


def markdown_cell(source: str) -> dict[str, object]:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def code_cell(source: str) -> dict[str, object]:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


def build_notebook() -> dict[str, object]:
    return {
        "cells": [
            markdown_cell(
                "# MovieMate: IMDb Conversational Chatbot\n\n"
                "This notebook documents the dataset exploration, preprocessing, retrieval design, "
                "and conversational prototype built from the provided IMDb Top 1000 dataset."
            ),
            markdown_cell(
                "## 1. Load the dataset\n\n"
                "The project uses a cleaned version of the provided CSV and imports the local project modules."
            ),
            code_cell(
                "from pathlib import Path\n"
                "import sys\n\n"
                "project_root = Path.cwd().resolve()\n"
                "if not (project_root / 'movie_mate').exists():\n"
                "    project_root = project_root.parent\n"
                "if str(project_root) not in sys.path:\n"
                "    sys.path.insert(0, str(project_root))\n\n"
                "from movie_mate import MovieChatbot, compute_insights, load_movies\n\n"
                "movies = load_movies(project_root / 'data' / 'imdb_top_1000.csv')\n"
                "len(movies)"
            ),
            markdown_cell(
                "## 2. Dataset exploration\n\n"
                "We summarize the dataset to understand ratings, runtimes, common genres, directors, and missing values."
            ),
            code_cell(
                "insights = compute_insights(movies)\n"
                "insights['summary']"
            ),
            code_cell(
                "insights['top_genres'][:5], insights['top_directors'][:5], insights['missing_fields']"
            ),
            markdown_cell(
                "## 3. Preprocessing notes\n\n"
                "- Standardized text fields for search.\n"
                "- Parsed runtime, votes, gross, and metascore into numeric values where possible.\n"
                "- Repaired the malformed `Apollo 13` release year.\n"
                "- Preserved missing metadata safely.\n"
            ),
            markdown_cell(
                "## 4. Retrieval and conversational logic\n\n"
                "The chatbot combines structured query parsing with TF-IDF retrieval over title, genre, cast, "
                "director, and overview text. Follow-up messages can refine the prior query state."
            ),
            code_cell(
                "bot = MovieChatbot(movies)\n"
                "session = None\n"
                "for query in [\n"
                "    'Suggest sci-fi movies released after 2010',\n"
                "    'Only those with IMDb rating above 8.0',\n"
                "    'Movies similar to Inception',\n"
                "    'Who directed The Godfather?'\n"
                "]:\n"
                "    response = bot.respond(query, session)\n"
                "    session = response['session_id']\n"
                "    print(query)\n"
                "    print(response['reply'])\n"
                "    print([card['title'] for card in response['cards'][:3]])\n"
                "    print('---')"
            ),
            markdown_cell(
                "## 5. Evaluation and reflection\n\n"
                "Strengths:\n"
                "- Handles natural-language filters for genre, year, actor, director, rating, and runtime.\n"
                "- Supports multi-turn refinement and title detail lookups.\n"
                "- Stays lightweight and reproducible without external dependencies.\n\n"
                "Limitations:\n"
                "- Response wording is template-based rather than generated by a live LLM.\n"
                "- Retrieval is lexical TF-IDF, so deeper semantic paraphrasing can still be improved.\n"
                "- The dataset is limited to the IMDb Top 1000 entries supplied in the CSV.\n"
            ),
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.14",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    project_root = Path(__file__).resolve().parent
    notebook_path = project_root / "notebooks" / "imdb_chatbot_analysis.ipynb"
    notebook_path.write_text(json.dumps(build_notebook(), indent=2), encoding="utf-8")
    print(f"Wrote {notebook_path}")


if __name__ == "__main__":
    main()
